name: Publish NPM Package

env:
  NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master

      - name: Setup node env ğŸ—ï¸
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Install dependencies ğŸ› ï¸
        run: npm install

      - name: Packing files ğŸ“¦
        run: npm pack

      - name: Add Auth Token to .npmrc file ğŸ’¢
        run: echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc

      - name: Publish new version âœ
        run: npm publish --access public
